### ISSUE TITLE
The conflict of file format between the trained models and the adamAttack models

### ISSUE THREAD

**Issue by Alentine** [TheAdamProject/adams#1]
Hello, I am really interested in this work, may I ask a question?

I have tried to use your code to train my models,and have got a model file of ‘**.h5’ keras format based on CNN networks. However, when I tried to use this 'h5' model to run the **adamsAttack**, it failed. It seems that the adamsAttack only accepts '***.pb' files.  

Can you do me a favor to tell me what to do so that I can run the adamsAttack using the models with '**.h5' trained by your codes?

**Comment by pasquini-dario** [comment]
Hello,

yes, sorry. I’ve just fixed that in the code for training.
You can convert your trained '.h5' model in the right format by doing something like this:

import tensorflow as tf
model_h5_path = '..../model.h5'
model_pb_path = '..../model' # it must not have the .h5 file extension 
model = tf.keras.models.load_model(model_h5_path)
model.save(model_pb_path, save_format='tf')

let me know if that works for you.

**Comment by Alentine** [comment]
It works! Thank you! : )
